CREATE DATABASE TP1B_EXAMENES
GO
USE TP1B_EXAMENES
GO 
CREATE TABLE CARRERAS(
IDCARRERA INT PRIMARY KEY,
CARRERA VARCHAR(50) NOT NULL
)
GO
CREATE TABLE MATERIAS(
IDMATERIA INT PRIMARY KEY,
IDCARRERA INT FOREIGN KEY REFERENCES CARRERAS (IDCARRERA) NOT NULL,
MATERIA VARCHAR(50) NOT NULL
)
GO
CREATE TABLE ALUMNOS(
LEGAJO INT PRIMARY KEY,
IDCARRERA INT FOREIGN KEY REFERENCES CARRERAS (IDCARRERA) NOT NULL,
DNI VARCHAR(10) NOT NULL UNIQUE,
NOMBRE VARCHAR (50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL,
MAIL VARCHAR(50) NOT NULL,
NACIMIENTO DATETIME NOT NULL CHECK (GETDATE() - NACIMIENTO >= 18)
)
GO
CREATE TABLE EXAMENES(
IDMATERIA INT NOT NULL FOREIGN KEY REFERENCES MATERIAS (IDMATERIA),
IDCARRERA INT NOT NULL FOREIGN KEY REFERENCES CARRERAS (IDCARRERA),
LEGAJO INT NOT NULL FOREIGN KEY REFERENCES ALUMNOS (LEGAJO),
FECHA DATETIME NOT NULL CHECK (FECHA <= GETDATE()),
NOTA INT NOT NULL CHECK (NOTA >= 0 AND NOTA <= 10)
PRIMARY KEY(LEGAJO,FECHA,IDMATERIA)
)