CREATE DATABASE TP1A_LIBRERIA
GO
USE TP1A_LIBRERIA
GO
CREATE TABLE PROVINCIAS(
  IDPROVINCIA INT NOT NULL PRIMARY KEY,
  PROVINCIA VARCHAR(50) NOT NULL
)
GO
CREATE TABLE LOCALIDADES(
  CODPOSTAL INT NOT NULL PRIMARY KEY,
  IDPROVINCIA INT NOT NULL FOREIGN KEY REFERENCES PROVINCIAS(IDPROVINCIA),
  LOCALIDAD VARCHAR(50) NOT NULL
)
GO
CREATE TABLE CLIENTES(
  DNI VARCHAR(10) NOT NULL PRIMARY KEY,
  APELLIDO VARCHAR(50) NOT NULL,
  NOMBRE VARCHAR(50) NOT NULL,
  SEXO CHAR(1) NOT NULL CHECK(SEXO = 'F' OR SEXO = 'M'),
  TELEFONO VARCHAR(15) NOT NULL,
  MAIL VARCHAR(15) NOT NULL,
  FECHA_ALTA DATE NOT NULL,
  FECHA_NACIMIENTO DATE NOT NULL,
  DIRECCION VARCHAR(50) NOT NULL,
  CODPOSTAL INT NOT NULL FOREIGN KEY REFERENCES LOCALIDADES(CODPOSTAL)
)
GO
CREATE TABLE VENDEDORES(
  LEGAJO INT NOT NULL PRIMARY KEY,
  DNI VARCHAR(10) NOT NULL UNIQUE,
  APELLIDO VARCHAR(50) NOT NULL,
  NOMBRE VARCHAR(50) NOT NULL,
  SEXO CHAR(1) NOT NULL CHECK(SEXO = 'F' OR SEXO = 'M'),
  TELEFONO VARCHAR(15) NOT NULL,
  FECHA_INGRESO DATE NOT NULL,
  FECHA_NACIMIENTO DATE NOT NULL,
  DIRECCION VARCHAR(50) NOT NULL,
  CODPOSTAL INT NOT NULL FOREIGN KEY REFERENCES LOCALIDADES(CODPOSTAL),
  SUELDO SMALLMONEY NOT NULL
)
GO
CREATE TABLE MARCAS(
  IDMARCA INT NOT NULL PRIMARY KEY,
  MARCA VARCHAR(50) NOT NULL
)
GO
CREATE TABLE TIPOS_ARTICULOS(
  IDTIPOARTICULO INT NOT NULL PRIMARY KEY,
  TIPO_ARTICULO VARCHAR(50) NOT NULL
)
GO
CREATE TABLE ARTICULOS(
  CODIGO VARCHAR(6) NOT NULL PRIMARY KEY,
  DESCRIPCION VARCHAR(255) NOT NULL,
  IDMARCA INT NULL FOREIGN KEY REFERENCES MARCAS(IDMARCA),
  IDTIPOARTICULO INT NOT NULL FOREIGN KEY REFERENCES TIPOS_ARTICULOS(IDTIPOARTICULO),
  PRECIO_COMPRA SMALLMONEY NOT NULL,
  PRECIO_VENTA SMALLMONEY NOT NULL,
  STOCK INT NOT NULL,
  STOCK_MINIMO INT NOT NULL,
  ESTADO BIT NOT NULL
)
GO
CREATE TABLE VENTAS(
  NROVENTA BIGINT NOT NULL PRIMARY KEY IDENTITY (1, 1),
  FECHA DATE NOT NULL,
  CLIENTE VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES CLIENTES (DNI),
  VENDEDOR INT NOT NULL FOREIGN KEY REFERENCES VENDEDORES (LEGAJO),
  FORMA_PAGO CHAR(1) NOT NULL CHECK (FORMA_PAGO = 'E' OR FORMA_PAGO = 'T'),
  IMPORTE MONEY NOT NULL --CAMPO CALCULABLE (ANALIZAR PRO Y CONTRAS DE INCLUIRLO)
)
GO
CREATE TABLE DETALLE_VENTA(
  NROVENTA BIGINT NOT NULL FOREIGN KEY REFERENCES VENTAS (NROVENTA),
  ARTICULO VARCHAR(6) NOT NULL FOREIGN KEY REFERENCES ARTICULOS (CODIGO),
  PRECIO SMALLMONEY NOT NULL,
  CANTIDAD INT NOT NULL,
  PRIMARY KEY (NROVENTA, ARTICULO)
)
